#!/bin/bash

set -e

_enable_munged() {
  if [ ! -f /etc/munge/munge.key ]; then
    /usr/sbin/create-munge-key
  fi
  cat <<EOF | tee /etc/supervisord.d/munge.ini
[program:munged]
command=/usr/sbin/munged --foreground
user=munge
priority=1
autostart=true
autorestart=true
EOF
}

_create_slurm_group_and_user() {
  if [ ! $(getent group slurm) ]; then
    if [[ "${SLURM_GROUP}" == "" ]]; then
      SLURM_GROUP=slurm
    fi
    groupadd ${SLURM_GROUP}
  fi
  if [ ! $(getent passwd slurm) ]; then 
    if [[ "${SLURM_USER}" == "" ]]; then
      SLURM_USER=slurm
    fi
    useradd -g ${SLURM_GROUP} ${SLURM_USER}
  fi
}

_create_slurm_directories() {
  mkdir -p /etc/slurm
  chown ${SLURM_USER}:${SLURM_GROUP} /etc/slurm
  mkdir -p /var/log/slurm
  chown ${SLURM_USER}:${SLURM_GROUP} /var/log/slurm
  mkdir -p /var/run/slurm
  chown ${SLURM_USER}:${SLURM_GROUP} /var/run/slurm
  mkdir -p /var/spool/slurm/slurmctld
  chown ${SLURM_USER}:${SLURM_GROUP} /var/spool/slurm/slurmctld
  mkdir -p /var/spool/slurm/slurmd
  chown ${SLURM_USER}:${SLURM_GROUP} /var/spool/slurm/slurmd
}

_enable_slurmdbd() {
  if [ ! -f /etc/slurm/slurmdbd.conf ]; then
    cat <<EOF | tee /etc/slurm/slurmdbd.conf
#
# Example slurmdbd.conf file.
#
# See the slurmdbd.conf man page for more information.
#
# Archive info
#ArchiveJobs=yes
#ArchiveDir="/tmp"
#ArchiveSteps=yes
#ArchiveScript=
#JobPurge=12
#StepPurge=1
#
# Authentication info
AuthType=auth/munge
#AuthInfo=/var/run/munge/munge.socket.2
#
# slurmDBD info
DbdAddr=${SLURMDBD_DBD_ADDR:-localhost}
DbdHost=${SLURMDBD_DBD_HOST:-localhost}
DbdPort=${SLURMDBD_DBD_PORT:-6819}
SlurmUser=${SLURM_USER}
#MessageTimeout=300
DebugLevel=4
#DefaultQOS=normal,standby
LogFile=/var/log/slurm/slurmdbd.log
PidFile=/var/run/slurm/slurmdbd.pid
#PluginDir=/usr/lib/slurm
#PrivateData=accounts,users,usage,jobs
#TrackWCKey=yes
#
# Database info
StorageType=accounting_storage/mysql
StorageHost=${SLURMDBD_STORAGE_HOST:-localhost}
StoragePort=${SLURMDBD_STORAGE_PORT:-3306}
StoragePass=${SLURMDBD_STORAGE_PASS:-password}
StorageUser=${SLURMDBD_STORAGE_USER:-slurm}
#StorageLoc=slurm_acct_db
EOF
  fi
  chown ${SLURM_USER}:${SLURM_GROUP} /etc/slurm/slurmdbd.conf
  chmod 600 /etc/slurm/slurmdbd.conf
  cat <<EOF | tee /etc/supervisord.d/slurmdbd.ini
[program:slurmdbd]
command=/usr/sbin/slurmdbd -D
user=slurm
priority=10
autostart=true
autorestart=true
EOF
}

_create_slurm_config() {
  if [ ! -f /etc/slurm/slurm.conf ]; then
    cat <<EOF | tee /etc/slurm/slurm.conf
#
# Example slurm.conf file. Please run configurator.html
# (in doc/html) to build a configuration file customized
# for your environment.
#
#
# slurm.conf file generated by configurator.html.
#
# See the slurm.conf man page for more information.
#
ClusterName=${SLURM_CLUSTER_NAME:-linux}
ControlMachine=${SLURM_CONTROL_MACHINE:-linux0}
#ControlAddr=
#BackupController=
#BackupAddr=
#
SlurmUser=${SLURM_USER}
#SlurmdUser=root
SlurmctldPort=${SLURM_SLURMCTLD_PORT:-6817}
SlurmdPort=${SLURM_SLURMD_PORT:-6818}
AuthType=auth/munge
#JobCredentialPrivateKey=
#JobCredentialPublicCertificate=
StateSaveLocation=/var/spool/slurm/slurmctld
SlurmdSpoolDir=/var/spool/slurm/slurmd
SwitchType=switch/none
MpiDefault=none
SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmdPidFile=/var/run/slurm/slurmd.pid
ProctrackType=proctrack/pgid
#PluginDir=
#FirstJobId=
ReturnToService=0
#MaxJobCount=
#PlugStackConfig=
#PropagatePrioProcess=
#PropagateResourceLimits=
#PropagateResourceLimitsExcept=
#Prolog=
#Epilog=
#SrunProlog=
#SrunEpilog=
#TaskProlog=
#TaskEpilog=
#TaskPlugin=
#TrackWCKey=no
#TreeWidth=50
#TmpFS=
#UsePAM=
#
# TIMERS
SlurmctldTimeout=300
SlurmdTimeout=300
InactiveLimit=0
MinJobAge=300
KillWait=30
Waittime=0
#
# SCHEDULING
SchedulerType=sched/backfill
#SchedulerAuth=
#SelectType=select/linear
SlurmdParameters=config_overrides
#PriorityType=priority/multifactor
#PriorityDecayHalfLife=14-0
#PriorityUsageResetPeriod=14-0
#PriorityWeightFairshare=100000
#PriorityWeightAge=1000
#PriorityWeightPartition=10000
#PriorityWeightJobSize=1000
#PriorityMaxAge=1-0
#
# LOGGING
SlurmctldDebug=3
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdDebug=3
SlurmdLogFile=/var/log/slurm/slurmd.log
JobCompType=jobcomp/none
#JobCompLoc=
#
# ACCOUNTING
#JobAcctGatherType=jobacct_gather/linux
#JobAcctGatherFrequency=30
#
AccountingStorageType=accounting_storage/slurmdbd
#AccountingStorageHost=
#AccountingStorageLoc=
#AccountingStoragePass=
#AccountingStorageUser=
#
# LICENSES
Licenses=matlab:5
#
# COMPUTE NODES
${SLURM_NODES:-NodeName=linux[1-32] Procs=1 State=UNKNOWN}
${SLURM_PARTITION:-PartitionName=debug Nodes=ALL Default=YES MaxTime=INFINITE State=UP}
EOF
  fi
  chown ${SLURM_USER}:${SLURM_GROUP} /etc/slurm/slurm.conf
}

_enable_slurmctld() {
  _create_slurm_config
  cat <<EOF | tee /etc/supervisord.d/slurmctld.ini
[program:slurmctld]
command=/usr/sbin/slurmctld -D
user=slurm
priority=20
autostart=true
autorestart=true
EOF
}

_enable_slurmd() {
  _create_slurm_config
  cat <<EOF | tee /etc/supervisord.d/slurmd.ini
[program:slurmd]
command=/usr/sbin/slurmd -D
user=root
priority=30
autostart=true
autorestart=true
EOF
}

if [[ "${MUNGED_ENABLED}" == "true" ]]; then
  _enable_munged
fi
_create_slurm_group_and_user
_create_slurm_directories
if [[ "${SLURMDBD_ENABLED}" == "true" ]]; then
  _enable_slurmdbd
fi
if [[ "${SLURMCTLD_ENABLED}" == "true" ]]; then
  _enable_slurmctld
fi
if [[ "${SLURMD_ENABLED}" == "true" ]]; then
  _enable_slurmd
fi

exec "${@}"
